services:
  redis:
    image: redis:7-alpine
    #    container_name: redis
    restart: always
    command: redis-server --requirepass 1redisalpine1
    #    command: redis-server --requirepass 1redisalpine1 --appendonly yes
    ports:
      - "6379:6379"
    #    volumes:
    #      - redis_data:/data
    environment:
      - TZ=Asia/Shanghai
#    networks:
#      - redis-network

#volumes:
#  redis_data:
#    driver: local

#networks:
#  redis-network:
#    driver: bridge
